---
- name: Verify HAProxy
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if HAProxy service is running
      systemd:
        name: haproxy
      register: haproxy_service

    - name: Verify HAProxy is listening on port 80
      wait_for:
        port: 80
        host: 0.0.0.0
        timeout: 10

    - name: Verify HAProxy stats page is accessible
      uri:
        url: "http://localhost:8404/stats"
        method: GET
        user: admin
        password: admin123
        force_basic_auth: yes
      register: stats_check

    - name: Check HAProxy configuration syntax
      command: haproxy -f /etc/haproxy/haproxy.cfg -c
      register: config_check
      changed_when: false

    - name: Verify HAProxy process is running
      command: pgrep haproxy
      register: haproxy_process
      changed_when: false

    - name: Display verification results
      debug:
        msg: |
          HAProxy verification completed:
          - Service active: {{ haproxy_service.status.ActiveState == 'active' }}
          - Port 80 accessible: {{ True }}
          - Stats page accessible: {{ stats_check.status == 200 }}
          - Configuration valid: {{ config_check.rc == 0 }}
          - Process running: {{ haproxy_process.rc == 0 }}