---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: envoy-test
    image: quay.io/ansible/molecule-ubuntu:22.04
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    published_ports:
      - 8080:8080
      - 9901:9901
provisioner:
  name: ansible
verifier:
  name: ansible