---
- name: Verify Envoy Proxy
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if Envoy service is running
      systemd:
        name: envoy
      register: envoy_service

    - name: Verify Envoy is listening on port 8080
      wait_for:
        port: 8080
        host: 0.0.0.0
        timeout: 10

    - name: Verify Envoy admin interface is accessible
      uri:
        url: "http://localhost:9901/ready"
        method: GET
      register: admin_check

    - name: Check Envoy configuration
      uri:
        url: "http://localhost:9901/config_dump"
        method: GET
      register: config_check

    - name: Verify Envoy process is running
      command: pgrep envoy
      register: envoy_process
      changed_when: false

    - name: Test proxy functionality
      uri:
        url: "http://localhost:8080/get"
        method: GET
      register: proxy_test
      failed_when: false

    - name: Display verification results
      debug:
        msg: |
          Envoy verification completed:
          - Service active: {{ envoy_service.status.ActiveState == 'active' }}
          - Port 8080 accessible: {{ True }}
          - Admin interface accessible: {{ admin_check.status == 200 }}
          - Configuration accessible: {{ config_check.status == 200 }}
          - Process running: {{ envoy_process.rc == 0 }}
          - Proxy test: {{ proxy_test.status | default('Failed') }}