---
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  become: true

- name: Create Elasticsearch directories
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: '0755'
  become: true
  loop:
    - "{{ elasticsearch_data_dir }}"
    - "{{ elasticsearch_log_dir }}"

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0660'
    backup: yes
  become: true
  notify: restart elasticsearch

- name: Configure Elasticsearch JVM options
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options.d/heap.options
    owner: root
    group: elasticsearch
    mode: '0660'
  become: true
  notify: restart elasticsearch

- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Wait for Elasticsearch to be ready
  uri:
    url: "http://localhost:{{ elasticsearch_port }}/_cluster/health"
    method: GET
    timeout: 60
  register: elasticsearch_health
  until: elasticsearch_health.status == 200
  retries: 12
  delay: 5