---
- name: Configure unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
  become: true

- name: Configure auto updates
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable automatic updates
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Perform full system upgrade
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  become: true
  register: apt_upgrade
  when: not security_updates_only

- name: Perform security updates only
  apt:
    upgrade: safe
    update_cache: yes
  become: true
  register: security_upgrade
  when: security_updates_only

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Notify about reboot requirement
  debug:
    msg: "System reboot is required after updates"
  when: reboot_required.stat.exists

- name: Reboot system if required and enabled
  reboot:
    reboot_timeout: 300
    post_reboot_delay: 30
  become: true
  when: 
    - reboot_required.stat.exists
    - auto_reboot_enabled