---
galaxy_info:
  author: Ansible Development Team
  description: ELK Stack logging setup for external log aggregation
  company: Internal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: common