---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install required packages
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
  become: true

- name: Add Envoy GPG key
  apt_key:
    url: https://getenvoy.io/gpg
    state: present
  become: true

- name: Add Envoy repository
  apt_repository:
    repo: "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb jammy stable"
    state: present
  become: true

- name: Install Envoy from getenvoy (fallback to manual install)
  block:
    - name: Try to install Envoy from repository
      apt:
        name: getenvoy-envoy
        state: present
        update_cache: yes
      become: true
  rescue:
    - name: Download Envoy binary manually
      get_url:
        url: "https://github.com/envoyproxy/envoy/releases/download/v{{ envoy_version }}.0/envoy-{{ envoy_version }}.0-linux-x86_64"
        dest: /usr/local/bin/envoy
        mode: '0755'
        owner: root
        group: root
      become: true

- name: Create Envoy user
  user:
    name: "{{ envoy_user }}"
    group: "{{ envoy_group }}"
    system: yes
    shell: /bin/false
    home: "{{ envoy_data_dir }}"
    create_home: no
  become: true

- name: Create Envoy directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ envoy_user }}"
    group: "{{ envoy_group }}"
    mode: '0755'
  become: true
  loop:
    - "{{ envoy_config_dir }}"
    - "{{ envoy_log_dir }}"
    - "{{ envoy_data_dir }}"

- name: Generate Envoy configuration
  template:
    src: envoy.yaml.j2
    dest: "{{ envoy_config_file }}"
    owner: "{{ envoy_user }}"
    group: "{{ envoy_group }}"
    mode: '0644'
    backup: yes
  become: true
  notify: restart envoy

- name: Create Envoy systemd service
  template:
    src: envoy.service.j2
    dest: "{{ envoy_systemd_unit }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: 
    - reload systemd
    - restart envoy

- name: Enable and start Envoy service
  systemd:
    name: "{{ envoy_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes
  become: true

- name: Verify Envoy is listening on configured ports
  wait_for:
    port: "{{ envoy_listener_port }}"
    host: 0.0.0.0
    delay: 2
    timeout: 30

- name: Verify Envoy admin interface
  wait_for:
    port: "{{ envoy_admin_port }}"
    host: 127.0.0.1
    delay: 2
    timeout: 30