---
# HAProxy specific group variables

# HAProxy tuning for server group
haproxy_global:
  chroot: /var/lib/haproxy
  stats:
    socket: /var/lib/haproxy/stats
    level: admin
  user: haproxy
  group: haproxy
  daemon: true
  maxconn: 4096
  ssl_default_bind_options: no-sslv3 no-tlsv10 no-tlsv11
  ssl_default_bind_ciphers: ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

haproxy_defaults:
  mode: http
  timeout:
    connect: 5000ms
    client: 50000ms
    server: 50000ms
  option:
    - httplog
    - dontlognull
    - http-server-close
    - forwardfor
    - redispatch
  retries: 3

# Default frontend configuration
haproxy_frontends:
  - name: web_frontend
    bind: "*:80"
    default_backend: web_servers
    capture:
      request: "header Host len 64"

# Default backend pointing to Envoy proxies
haproxy_backends:
  - name: web_servers
    balance: roundrobin
    option:
      - httpchk GET /ready
    servers:
      - name: envoy1
        address: "{{ hostvars['envoy-01']['ansible_host'] }}:8080"
        check: true
      - name: envoy2
        address: "{{ hostvars['envoy-02']['ansible_host'] }}:8080"
        check: true

# Stats configuration
haproxy_stats:
  enabled: true
  uri: /stats
  realm: "HAProxy Statistics"
  auth:
    user: admin
    password: "{{ haproxy_stats_password | default('admin123') }}"