---
- name: Converge - Deploy common infrastructure
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: common
    - role: templates

- name: Converge - Deploy HAProxy servers (failure test)
  hosts: haproxy_servers
  become: true
  gather_facts: true
  roles:
    - role: haproxy

- name: Converge - Deploy Envoy Proxy servers (failure test)
  hosts: envoy_servers
  become: true
  gather_facts: true
  roles:
    - role: envoyproxy