---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: common
    - role: haproxy
      when: "'haproxy' in group_names or inventory_hostname in groups.get('haproxy_servers', [])"
    - role: envoyproxy
      when: "'envoy' in group_names or inventory_hostname in groups.get('envoy_servers', [])"