---
- name: Converge - Standard Ansible Module Test
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Test file operations (no network required)
      file:
        path: /tmp/molecule-success
        state: directory
        mode: '0755'

    - name: Create test directory
      file:
        path: /home/molecule-test
        state: directory
        mode: '0755'

    - name: Create test file
      copy:
        content: "Molecule test successful at {{ ansible_date_time.iso8601 }}!"
        dest: /home/molecule-test/success.txt
        mode: '0644'

    - name: Verify test file exists
      stat:
        path: /home/molecule-test/success.txt
      register: test_file

    - name: Display test results
      debug:
        msg: 
          - "🎉 SUCCESS: Test file exists: {{ test_file.stat.exists }}"
          - "📁 File path: {{ test_file.stat.path | default('N/A') }}"
          - "📏 File size: {{ test_file.stat.size | default('N/A') }} bytes"

    - name: Assert test completed successfully
      assert:
        that:
          - test_file.stat.exists
          - test_file.stat.isreg
        fail_msg: "❌ Test file was not created successfully"
        success_msg: "✅ All molecule tests passed with standard Ansible modules!"
