---
dependency:
  name: galaxy
  options:
    requirements-file: collections/requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-instance
    image: quay.io/ansible/molecule-ubuntu:22.04
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: molecule-network
        ipv4_address: 172.20.0.10

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
      stdout_callback: yaml
      bin_ansible_callbacks: true
  playbooks:
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      ubuntu-instance:
        ansible_user: ansible

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy