---
all:
  children:
    proxies:
      children:
        haproxy_servers:
          hosts:
            haproxy-01:
              ansible_host: 172.20.0.10
              ansible_user: ansible
            haproxy-02:
              ansible_host: 172.20.0.11
              ansible_user: ansible
        envoy_servers:
          hosts:
            envoy-01:
              ansible_host: 172.20.0.20
              ansible_user: ansible
            envoy-02:
              ansible_host: 172.20.0.21
              ansible_user: ansible
    infrastructure:
      children:
        common_servers:
          hosts:
            common-01:
              ansible_host: 172.20.0.30
              ansible_user: ansible
            common-02:
              ansible_host: 172.20.0.31
              ansible_user: ansible
    logging:
      hosts:
        log-server:
          ansible_host: 172.20.0.40
          ansible_user: ansible