---
- name: Development Environment Setup
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Development-specific variables
    auto_reboot_enabled: false
    security_updates_only: false
    ufw_enabled: false
    fail2ban_enabled: false
    monitoring_enabled: true
    
  roles:
    - role: common
    - role: templates

- name: Setup HAProxy for Development
  hosts: haproxy_servers
  become: true
  gather_facts: true
  vars:
    haproxy_backends:
      - name: dev_backend
        balance: roundrobin
        option:
          - httpchk GET /health
        servers:
          - name: dev1
            address: "httpbin.org:80"
            check: true
          - name: dev2
            address: "httpbin.org:80" 
            check: true
            backup: true
  roles:
    - role: haproxy

- name: Setup Envoy for Development  
  hosts: envoy_servers
  become: true
  gather_facts: true
  vars:
    envoy_clusters:
      - name: dev_service
        connect_timeout: 30s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: dev_service
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: httpbin.org
                        port_value: 80
  roles:
    - role: envoyproxy