---
galaxy_info:
  author: Ansible Development Team
  description: Common infrastructure setup including certificates, OS patches, filebeat
  company: Internal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []